version: '3.4'

services:

  database:
     image: mongo:latest
     ports:
      - 27017:27017
     volumes:
       - mongodb_data_container:/data/db

  grand.web:
    depends_on:
       - database
    image: ${DOCKER_REGISTRY-}grandweb
    ulimits:
        nofile:
            soft: 1048576
            hard: 1048576
    build:
      context: .
      dockerfile: Grand.Web/Dockerfile

volumes:
  mongodb_data_container: